<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Mockbench-36a6db13-7efb-42ce-aab6-ef3d8ac0bdb9</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Mockbench.Abstractions\Mockbench.Abstractions.csproj" />
		<ProjectReference Include="..\Mockbench.Api\Mockbench.Api.csproj" />
		<ProjectReference Include="..\Mockbench.Client\Mockbench.Client.csproj" />
		<ProjectReference Include="..\Mockbench.Data.Sqlite\Mockbench.Data.Sqlite.csproj" />
		<ProjectReference Include="..\Mockbench.Data.SqlServer\Mockbench.Data.SqlServer.csproj" />
		<ProjectReference Include="..\Mockbench.Data\Mockbench.Data.csproj" />
		<ProjectReference Include="..\Mockbench.Services\Mockbench.Services.csproj" />
		<ProjectReference Include="..\Mockbench.Shared\Mockbench.Shared.csproj" />
	</ItemGroup>
	
</Project>
